### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Sage0101** [d07RiV/SNOParser#3]
This was my favorite tool, can this please be updated ? I'm trying to build this but its missing poe.cpp and inet.cpp :(

**Comment by d07RiV** [comment]
Did you mean https://github.com/d07RiV/AutoParser ? Because SNOParser doesn't do anything on its own, its just a collection of code I use for various tasks, whereas AutoParser is a more specialized tool for extracting D3 data with a better interface. They made a small change in their CDN config that prevents us from getting a list of all previous (and future) builds, so it will only be able to extract the current live or PTR builds, which is a bummer, but yeah I'll update it soon.

**Comment by d07RiV** [comment]
Updated the tool at http://www.rivsoft.net/projects/other/snoparser/

This repository is out of date btw, it is hard for me to update it since there's some stuff I don't want to make public, and its a mess overall.

**Comment by Sage0101** [comment]
they broke casc viewer and most of your stuff with diablo 2.5.0 test realm.
is there a way to fix it?
